---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: ['unzip', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']

- name: Install python
  apt:
    name: "{{ item }}"
    state: latest
  loop: ['python3','python3-pip', 'python3-setuptools']

- name: Add docker repo key
  apt_key:
    url: "{{ docker_repo_key }}"
    state: present

- name: Add docker repo
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present

- name: Install docker
  apt:
    name: "docker-ce"
    state: latest
    update_cache: yes

- name: Install Docker SDK for Python
  pip:
    name: docker
    state: latest
    executable: pip3