---
python_version: 3
install_as_service: False
jupyter_service_name: jupyter

livy_service_name: livy
livy_base_dir: /opt
livy_file_name: livy-0.5.0-incubating-bin
livy_download_url: "http://archive.apache.org/dist/incubator/livy/0.5.0-incubating/livy-0.5.0-incubating-bin.zip"
livy_home: "{{ livy_base_dir }}/{{ livy_file_name }}"