---

- name: Check munge dir
  become: true
  file:
    path: /etc/munge
    owner: munge
    group: munge
    mode: 0700
    state: directory

- name: Install munge key
  become: true
  copy:
    src: "{{ DIR_TO_INSTALL_MUNGE_KEY }}/munge.key"
    dest: /etc/munge/munge.key
    force: yes
    owner: munge
    group: munge
    mode: 0400
  notify: restart munge


- name: Ensure Munge is enabled and running
  become: yes
  service:
    name: munge
    enabled: yes
    state: started



